# Simple ANN for predicting if customer will close the bank account

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Step 1 - Data Preprocessing

### loading the dataset and separating features (X) and label (y)

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(dataset)

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling (using inbuilt standard technique)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Step 2 - Building the ANN

### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Step 3 - Training the ANN

### Compiling the ANN (using binary_crossentropy loss function as the goal is binary classification)

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 437us/step - loss: 0.5975 - accuracy: 0.6435
Epoch 2/100
250/250 [==============================] - 0s 419us/step - loss: 0.4566 - accuracy: 0.7951
Epoch 3/100
250/250 [==============================] - 0s 437us/step - loss: 0.4368 - accuracy: 0.7989
Epoch 4/100
250/250 [==============================] - 0s 558us/step - loss: 0.4287 - accuracy: 0.7993
Epoch 5/100
250/250 [==============================] - 0s 462us/step - loss: 0.4218 - accuracy: 0.8035
Epoch 6/100
250/250 [==============================] - 0s 409us/step - loss: 0.4127 - accuracy: 0.8109
Epoch 7/100
250/250 [==============================] - 0s 701us/step - loss: 0.4002 - accuracy: 0.8219
Epoch 8/100
250/250 [==============================] - 0s 434us/step - loss: 0.3870 - accuracy: 0.8274
Epoch 9/100
250/250 [==============================] - 0s 438us/step - loss: 0.3766 - accuracy: 0.8374
Epoch 10/100
250/250 [==============================] - 0s 440us/step - l

250/250 [==============================] - 0s 421us/step - loss: 0.3393 - accuracy: 0.8611
Epoch 80/100
250/250 [==============================] - 0s 516us/step - loss: 0.3391 - accuracy: 0.8601
Epoch 81/100
250/250 [==============================] - 0s 432us/step - loss: 0.3395 - accuracy: 0.8604
Epoch 82/100
250/250 [==============================] - 0s 398us/step - loss: 0.3389 - accuracy: 0.8615
Epoch 83/100
250/250 [==============================] - 0s 416us/step - loss: 0.3386 - accuracy: 0.8614
Epoch 84/100
250/250 [==============================] - 0s 411us/step - loss: 0.3386 - accuracy: 0.8622
Epoch 85/100
250/250 [==============================] - 0s 400us/step - loss: 0.3383 - accuracy: 0.8620
Epoch 86/100
250/250 [==============================] - 0s 408us/step - loss: 0.3380 - accuracy: 0.8621
Epoch 87/100
250/250 [==============================] - 0s 421us/step - loss: 0.3379 - accuracy: 0.8619
Epoch 88/100
250/250 [==============================] - 0s 429us/step - loss:

## Step 4 - Evaluating the model

### Predicting the Test set results

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1518   77]
 [ 202  203]]


0.8605